import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "./navbar";
import React,{useContext} from 'react'

const inter = Poppins({ subsets: ["latin"], weight: ["400", "500"] }); //used to be Monda

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const redirectUri = typeof window !== 'undefined' ? window.location.origin : '';
  return (
    <html lang="en">
        <body className={inter.className}><Navbar>{children}</Navbar></body>
    </html>
  );
}
